#!/usr/bin/env bash
#
# NRPE plugin to update apt repository
#

sudo apt-get update >/dev/null

if [ "X$?" == "X0" ]; then
    echo "Apt repository updated successfully"
else
    echo "Warning - error occured while updating apt repository"
    exit 1
fi
